USE [master]
GO

/****** Object:  Database [ElectronicsShopDB]    Script Date: 17.01.2026 6:33:39 ******/
CREATE DATABASE [ElectronicsShopDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ElectronicsShopDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.IPCHSERVER\MSSQL\DATA\ElectronicsShopDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ElectronicsShopDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.IPCHSERVER\MSSQL\DATA\ElectronicsShopDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ElectronicsShopDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ElectronicsShopDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ElectronicsShopDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ElectronicsShopDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ElectronicsShopDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ElectronicsShopDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ElectronicsShopDB] SET  MULTI_USER 
GO

ALTER DATABASE [ElectronicsShopDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ElectronicsShopDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ElectronicsShopDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ElectronicsShopDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ElectronicsShopDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ElectronicsShopDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ElectronicsShopDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ElectronicsShopDB] SET  READ_WRITE 
GO

